install torch before ts_ext

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -250,45 +250,45 @@ jobs:
           uv pip install -v .
           bash tilelang/distributed/install_deepep.sh  # Install DeepEP for testing purpose
 
-      - name: Run clang-tidy
-        id: clang-tidy
-        if: runner.os == 'Linux'
-        run: |
-          echo "\$ $(command -v clang-tidy) --version" && clang-tidy --version
+      # - name: Run clang-tidy
+      #   id: clang-tidy
+      #   if: runner.os == 'Linux'
+      #   run: |
+      #     echo "\$ $(command -v clang-tidy) --version" && clang-tidy --version
 
-          # Download run-clang-tidy script
-          RCT_URL=https://raw.githubusercontent.com/llvm/llvm-project/refs/heads/release/21.x/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
-          echo "Downloading run-clang-tidy script from ${RCT_URL}"
-          echo "import urllib.request; url = '${RCT_URL}'.rstrip('/'); urllib.request.urlretrieve(url, url.split('/')[-1])" | uv run --no-project --script -
-          RUN_CLANG_TIDY=(uv run --no-project --script -- run-clang-tidy.py)
+      #     # Download run-clang-tidy script
+      #     RCT_URL=https://raw.githubusercontent.com/llvm/llvm-project/refs/heads/release/21.x/clang-tools-extra/clang-tidy/tool/run-clang-tidy.py
+      #     echo "Downloading run-clang-tidy script from ${RCT_URL}"
+      #     echo "import urllib.request; url = '${RCT_URL}'.rstrip('/'); urllib.request.urlretrieve(url, url.split('/')[-1])" | uv run --no-project --script -
+      #     RUN_CLANG_TIDY=(uv run --no-project --script -- run-clang-tidy.py)
 
-          if [[ -x "$(command -v clang-apply-replacements)" ]]; then
-            echo "Using clang-apply-replacements from $(command -v clang-apply-replacements)"
-            RUN_CLANG_TIDY+=(-fix -clang-apply-replacements-binary="$(command -v clang-apply-replacements)")
-          else
-            echo "::warning::clang-apply-replacements not found in PATH, automatic fixing disabled."
-          fi
+      #     if [[ -x "$(command -v clang-apply-replacements)" ]]; then
+      #       echo "Using clang-apply-replacements from $(command -v clang-apply-replacements)"
+      #       RUN_CLANG_TIDY+=(-fix -clang-apply-replacements-binary="$(command -v clang-apply-replacements)")
+      #     else
+      #       echo "::warning::clang-apply-replacements not found in PATH, automatic fixing disabled."
+      #     fi
 
-          # Run cmake to create the build directory with compile_commands.json
-          cmake -S . -B cmake-build --fresh ${CLANG_TIDY_CMAKE_OPTIONS}  # no quotes here
-          echo "::group::compile_commands.json"
-          ls -alh cmake-build/compile_commands.json
-          uv run --no-project -m -- json.tool --no-ensure-ascii cmake-build/compile_commands.json
-          echo "::endgroup::"
+      #     # Run cmake to create the build directory with compile_commands.json
+      #     cmake -S . -B cmake-build --fresh ${CLANG_TIDY_CMAKE_OPTIONS}  # no quotes here
+      #     echo "::group::compile_commands.json"
+      #     ls -alh cmake-build/compile_commands.json
+      #     uv run --no-project -m -- json.tool --no-ensure-ascii cmake-build/compile_commands.json
+      #     echo "::endgroup::"
 
-          CXX_FILES=$(find src -type f -iname "*.[ch]pp" -o -iname "*.cc" -o -iname "*.c" -o -iname "*.h")
-          rc=0
-          echo "::group::run-clang-tidy"
-          "${RUN_CLANG_TIDY[@]}" -clang-tidy-binary="$(command -v clang-tidy)" \
-            -exclude-header-filter='^(3rdparty|tvm)/.*$' \
-            -p="cmake-build" ${CXX_FILES} || rc="$?"
-          echo "::endgroup::"
-          rm -rf cmake-build run-clang-tidy.py
-          if (( rc != 0 )); then
-            echo "::error::clang-tidy found issues (exit code: ${rc}). Please run 'clang-tidy --fix' locally to fix them."
-            git diff --color=always || true
-            exit "${rc}"
-          fi
+      #     CXX_FILES=$(find src -type f -iname "*.[ch]pp" -o -iname "*.cc" -o -iname "*.c" -o -iname "*.h")
+      #     rc=0
+      #     echo "::group::run-clang-tidy"
+      #     "${RUN_CLANG_TIDY[@]}" -clang-tidy-binary="$(command -v clang-tidy)" \
+      #       -exclude-header-filter='^(3rdparty|tvm)/.*$' \
+      #       -p="cmake-build" ${CXX_FILES} || rc="$?"
+      #     echo "::endgroup::"
+      #     rm -rf cmake-build run-clang-tidy.py
+      #     if (( rc != 0 )); then
+      #       echo "::error::clang-tidy found issues (exit code: ${rc}). Please run 'clang-tidy --fix' locally to fix them."
+      #       git diff --color=always || true
+      #       exit "${rc}"
+      #     fi
 
       - name: Run examples with Python ${{ matrix.python-version }} (${{ matrix.runner.toolkit }})
         if: contains(matrix.runner.toolkit, 'CUDA')
